### ISSUE TITLE
Component imagePullPolicy is IfNotPresent

### ISSUE THREAD

**Issue by iamalnewkirk** [kalmhq/kalm#229]
Having the component `imagePullPolicy` as `IfNotPresent` means that an update to an image tag, e.g. `latest`, won't results in a proper refresh when the component is scaled or restarted.

Excerpt from Kalm created pod, `kubectl describe` command:
```
spec:
  containers:
  - image: $CONTAINER_REGISTRY/$CONTAINER_IMAGE:$IMAGE_TAG
    imagePullPolicy: IfNotPresent
```
